### ISSUE TITLE
File Upload

### ISSUE THREAD

**Issue by aniruddhasanyal** [rosinality/knotter#9]
I got it installed successfully and am trying to upload a .csv file by clicking on the browse button, but it's not getting uploaded as the data is not displayed on the left panel. Please help. I am using python 3.6. TIA

**Comment by rosinality** [comment]
Error logs would be printed in the console. Can I get an error logs?

**Comment by aniruddhasanyal** [comment]
Hi, thanks for replying. Below is the console output after launching knotter:

`Serving at port 8000
Server started at http://localhost:9000
[7250:7288:0213/172337.296268:ERROR:browser_gpu_channel_host_factory.cc(121)] Failed to launch GPU process.
Created new window in existing browser session.
127.0.0.1 - - [13/Feb/2018 17:23:37] code 404, message File not found
127.0.0.1 - - [13/Feb/2018 17:23:37] "GET /bower_components/paper-listbox/paper-listbox.html HTTP/1.1" 404 -
/usr/local/lib/python3.6/dist-packages/knotter/server.py:419: RuntimeWarning: coroutine 'WebSocketResponse.send_str' was never awaited
  self.ws.send_str(json.dumps(content))`

Please let me know if this is useful.

**Comment by aniruddhasanyal** [comment]
I reinstalled knotter, now it is showing the following output in the console:

[knotter.log](https://github.com/rosinality/knotter/files/1721686/knotter.log)

**Comment by rosinality** [comment]
Hopefully 84a4f34eb5402ca00db46f861a2730985ccab52a will resolve the error.

**Comment by aniruddhasanyal** [comment]
Thanks a lot :), this is working like charm. And thanks a lot for this project.
